# Site
name: "Mirae the Future"
title: "Mirae the Future"
description: "Hello World!"
logo: 'assets/images/logo1_mirae.png'
favicon: 'assets/images/favicon1_mirae.png'
baseurl: https://miraethefuture.github.io/
google_analytics: 'G-CYDFEWC2YE'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: miraeaeaeaeae@gmail.com

# Authors
authors:
  Mirae:
    name: Mirae
    display_name: Mirae
    avatar: 'assets/images/mirae_memoji.png'
    email: miraeaeaeaeae@gmail.com
    web: https://miraethefuture.github.io/
    twitter: https://twitter.com/Lookingfortheb4
    description: "a developer who is an artist"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
#kramdown:
  #input : GFN
  #syntax_highlighter : rouge
   #syntax_highlighter_opts:
      #disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
